# -*- coding: utf-8 -*-
"""Inhalte der RuhrCargo-Website. Einzige Quelle für alle Seitentexte."""

SITE = {
    "name": "RuhrCargo GmbH",
    "legal_name": "RuhrCargo GmbH",
    "claim": "Ihre Ware. Unser Auftrag.",
    # EINZIGE Stelle für die Produktionsdomain. Sie steuert Canonicals,
    # Sitemap, robots.txt und Open Graph. Vor dem Livegang prüfen!
    "domain": "https://www.ruhrcargo.net",
    "ceo": "Melih Arik",
    "email": "info@ruhrcargo.net",
    "street": "Florianstraße 15-21",
    "zip": "44139",
    "city": "Dortmund",
    "region": "Nordrhein-Westfalen",
    "court": "Amtsgericht Dortmund",
    "hrb": "HRB 38662",
    # TODO:TELEFON — vom Kunden noch nicht geliefert. § 5 DDG verlangt eine
    # Telefonnummer. Bis dahin Platzhalter; bewusst NICHT in den strukturierten
    # Daten, damit Google keine falsche Nummer ausliefert.
    "phone_display": "+49 (0) 231 000 00 00",
    "phone_href": "+492310000000",
    "phone_is_placeholder": True,
    # TODO:ZEITEN — vom Kunden nicht bestätigt, daher nicht in den strukturierten Daten
    "hours": "Mo – Fr, 07:00 – 18:00 Uhr",
    "hours_is_placeholder": True,
}


# ── Leistungen ────────────────────────────────────────────────────────────
SERVICES = [
 {
  "slug": "neumoebel-lieferung",
  "seo_title": "Neumöbel-Lieferung & Möbeltransport | RuhrCargo",
  "seo_desc": "Neumöbel liefern lassen: Wir transportieren Möbel vom Hersteller oder Lager bis zur Wunschadresse – im Möbelkoffer, gesichert und nach fester Terminabsprache.", "short": "Möbel vom Lager bis in die Wohnung", "nav": "Neumöbel", "title": "Neumöbel",
  "icon": "i-sofa", "num": "01", "img": "ruhrcargo-neumoebel-lieferung",
  "img_alt": "Zwei Mitarbeiter tragen ein verpacktes Sofa in einen Wohnraum",
  "teaser": "Empfindliche Neuware vom Lager bis zur Wunschadresse – sorgfältig verladen, sauber zugestellt.",
  "lead": "Neuware verzeiht keine Kratzer. Wir bringen Möbel vom Hersteller oder Lager bis zur Wunschadresse – gesichert, terminiert und ohne Umweg.",
  "body": [
    "Möbel sind sperrig, empfindlich und oft teuer. Ein Transportschaden kostet nicht nur Geld, sondern vor allem Zeit: für die Reklamation, für den Ersatz und für einen zweiten Anlauf. Deshalb behandeln wir Neumöbel wie das, was sie sind – Ware, die beim ersten Mal ankommen muss.",
    "Wir fahren für Möbelhäuser, Hersteller und Innenausstatter genauso wie für Privatkunden, die ihre Neuanschaffung nicht selbst transportieren wollen. Vom einzelnen Sessel bis zur kompletten Einrichtung.",
  ],
  "does": [
    "Abholung beim Hersteller, Lager oder Händler",
    "Ladungssicherung für empfindliche Oberflächen",
    "Transport im Möbelkoffer mit großem Ladevolumen",
    "Zustellung nach fester Terminabsprache",
    "Einzelstücke ebenso wie komplette Einrichtungen",
    "Feste Ansprechpartner von der Anfrage bis zur Lieferung",
  ],
  "who": ["Möbelhäuser und Fachhandel", "Hersteller und Zulieferer",
          "Innenausstatter und Raumausstatter", "Privatkunden mit Neuanschaffungen"],
  "vehicles": ["Möbelkoffer", "Koffer-LKW"],
  "faq": [
    ("Transportieren Sie auch einzelne Möbelstücke?",
     "Ja. Vom einzelnen Sessel bis zur kompletten Einrichtung. Sagen Sie uns, was zu transportieren ist – wir wählen das passende Fahrzeug dazu aus."),
    ("Wie wird die Ware gegen Schäden gesichert?",
     "Empfindliche Oberflächen werden abgedeckt, die Ladung im Fahrzeug so verzurrt, dass nichts verrutscht. Verpackte Neuware bleibt in ihrer Originalverpackung."),
    ("Können Sie in obere Etagen liefern?",
     "Sprechen Sie uns bei der Anfrage darauf an. Zugang, Etage und Treppenhaus klären wir vorab, damit vor Ort nichts improvisiert werden muss."),
  ],
  "related": ["umzuege", "elektrogeraete-lieferung", "stueckguttransport"],
 },
 {
  "slug": "elektrogeraete-lieferung",
  "seo_title": "Elektrogeräte liefern lassen | RuhrCargo Spedition",
  "seo_desc": "Waschmaschine, Kühlschrank, Fernseher: Wir transportieren Elektrogeräte und weiße Ware mit Ladebordwand – für Fachhandel, Küchenstudios und Privatkunden.", "short": "Weiße Ware und Elektronik", "nav": "Elektrogeräte", "title": "Elektrogeräte",
  "icon": "i-appliance", "num": "02", "img": "ruhrcargo-elektrogeraete-lieferung",
  "img_alt": "Mitarbeiter schiebt eine Waschmaschine über die Rampe in den Transporter",
  "teaser": "Weiße Ware und Elektronik sicher gesichert, sicher verladen und termingerecht zugestellt.",
  "lead": "Waschmaschine, Kühlschrank, Fernseher: Elektrogeräte sind schwer, empfindlich und schlecht zu greifen. Wir transportieren sie so, dass sie funktionsfähig ankommen.",
  "body": [
    "Weiße Ware verträgt weder harte Stöße noch falsche Lage. Wir sichern jedes Gerät einzeln, transportieren es aufrecht, wo das nötig ist, und stellen es am Ziel dort ab, wo es hingehört.",
    "Für den Fachhandel übernehmen wir wiederkehrende Touren zu Filialen und Endkunden. Für Privatkunden fahren wir Einzelgeräte – auch dann, wenn der Händler keine Lieferung anbietet.",
  ],
  "does": [
    "Einzelgeräte und komplette Filialbelieferungen",
    "Transportsicherung für empfindliche Technik",
    "Transport mit Ladebordwand statt Tragen über Bordkante",
    "Feste Touren für den Fachhandel auf Wunsch",
    "Zustellung nach Terminabsprache",
    "Abholung direkt beim Hersteller oder Großhandel",
  ],
  "who": ["Elektrofachhandel und Filialisten", "Küchenstudios",
          "Hersteller und Großhandel", "Privatkunden"],
  "vehicles": ["Koffer-LKW", "Kleintransporter"],
  "faq": [
    ("Übernehmen Sie auch wiederkehrende Filialbelieferungen?",
     "Ja. Feste Touren lassen sich planen und sind für beide Seiten kalkulierbar. Sprechen Sie uns auf Ihren Rhythmus an."),
    ("Wird das Gerät bis in die Wohnung gebracht?",
     "Das klären wir bei der Anfrage. Zugang, Etage und Stellplatz gehören zur Planung, damit vor Ort alles vorbereitet ist."),
    ("Was passiert bei einem Transportschaden?",
     "Wir dokumentieren die Übergabe. Melden Sie einen Schaden bitte direkt bei der Anlieferung, dann klären wir das Weitere unmittelbar mit Ihnen."),
  ],
  "related": ["neumoebel-lieferung", "stueckguttransport", "kurierdienst"],
 },
 {
  "slug": "stueckguttransport",
  "seo_title": "Stückguttransport | RuhrCargo Spedition Dortmund",
  "seo_desc": "Stückgut transportieren ohne Umladung: Von der Einzelpalette bis zur Teilladung fahren wir im Direktverkehr deutschlandweit – ab dem Ruhrgebiet, termingerecht.", "short": "Paletten, Kisten, Einzelsendungen", "nav": "Stückgut", "title": "Stückgut",
  "icon": "i-pallet", "num": "03", "img": "ruhrcargo-stueckguttransport",
  "img_alt": "Gabelstapler setzt eine folierte Palette im Lager ab",
  "teaser": "Paletten, Kisten und Einzelsendungen – flexibel gebündelt und deutschlandweit unterwegs.",
  "lead": "Von der Einzelpalette bis zur Teilladung: Wir bündeln Ihre Sendungen, planen die Route und liefern deutschlandweit – ohne Umweg über fremde Umschlagzentren.",
  "body": [
    "Stückgut über ein großes Netzwerk zu verschicken heißt: mehrfaches Umladen, viele Hände, wenig Kontrolle. Wir fahren stattdessen direkt. Ihre Palette wird einmal verladen und einmal abgeladen.",
    "Das ist besonders dann von Vorteil, wenn die Ware empfindlich ist, der Termin eng oder die Sendung zu groß für den Paketdienst und zu klein für eine Komplettladung.",
  ],
  "does": [
    "Einzelpaletten bis zur Teilladung",
    "Gitterboxen, Kisten und sperrige Einzelstücke",
    "Direktverkehr ohne Umladung",
    "Deutschlandweite Zustellung ab dem Ruhrgebiet",
    "Be- und Entladung per Gabelstapler oder Ladebordwand",
    "Feste Ansprechpartner in der Disposition",
  ],
  "who": ["Industrie und Produktion", "Groß- und Fachhandel",
          "Zulieferer", "Handwerksbetriebe"],
  "vehicles": ["Koffer-LKW", "Kleintransporter"],
  "faq": [
    ("Ab welcher Menge lohnt sich der Direktverkehr?",
     "Schon ab einer Palette, wenn Termin oder Empfindlichkeit der Ware im Vordergrund stehen. Wir sagen Ihnen ehrlich, wann eine andere Lösung günstiger ist."),
    ("Können Sie mehrere Empfänger auf einer Tour beliefern?",
     "Ja, das ist der Regelfall. Wir planen die Route so, dass die Reihenfolge zu Ihren Zeitfenstern passt."),
    ("Brauchen wir am Ziel einen Stapler?",
     "Nicht zwingend. Sagen Sie uns bei der Anfrage, wie am Empfangsort entladen werden kann – danach wählen wir das Fahrzeug aus."),
  ],
  "related": ["elektrogeraete-lieferung", "kurierdienst", "neumoebel-lieferung"],
 },
 {
  "slug": "kurierdienst",
  "seo_title": "Kurierdienst & Direktfahrten | RuhrCargo",
  "seo_desc": "Kurierfahrt mit Direktzustellung: ein Fahrzeug, eine Ladung, ein Ziel. Ohne Zwischenstopp und ohne Umladen – deutschlandweit und kurzfristig beauftragbar.", "short": "Direktfahrt ohne Umladung", "nav": "Kurierfahrten", "title": "Kurierfahrten",
  "icon": "i-bolt", "num": "04", "img": "ruhrcargo-kurierdienst",
  "img_alt": "Kurierfahrer bringt eine Sendung zu einem Bürogebäude, Transporter am Straßenrand",
  "teaser": "Direktfahrten, wenn es schnell gehen muss: ein Fahrzeug, eine Ladung, ein Ziel.",
  "lead": "Wenn ein Termin steht und die Sendung nicht warten kann: Ein Fahrzeug, eine Ladung, ein Ziel. Ohne Zwischenstopp, ohne Umladen.",
  "body": [
    "Die Direktfahrt ist die schnellste Form des Transports, weil sie die üblichen Zwischenschritte auslässt. Ihre Sendung wird bei Ihnen geladen und beim Empfänger abgeladen – dazwischen passiert nichts.",
    "Das ist die richtige Lösung für Ersatzteile, die eine Produktion am Laufen halten, für Unterlagen, die zu einem Termin vorliegen müssen, und für alles, wo ein verpasster Tag teurer ist als die Fahrt.",
  ],
  "does": [
    "Direktfahrt ohne Umladung und Zwischenlager",
    "Kurzfristige Beauftragung möglich",
    "Einzelsendungen bis zur Transporterladung",
    "Deutschlandweit, auch über Nacht geplant",
    "Feste Ansprechpartner während der Fahrt",
    "Auch für empfindliche und dokumentenpflichtige Ware",
  ],
  "who": ["Produktion und Instandhaltung", "Handel und Fachhandel",
          "Agenturen und Dienstleister", "Sanitätshäuser und Praxen"],
  "vehicles": ["Kleintransporter", "Koffer-LKW"],
  "faq": [
    ("Wie kurzfristig können Sie fahren?",
     "Das hängt davon ab, welches Fahrzeug frei ist. Rufen Sie an – am Telefon können wir Ihnen am schnellsten sagen, was heute noch machbar ist."),
    ("Fahren Sie auch nachts oder am Wochenende?",
     "Sprechen Sie uns auf Ihren Termin an. Was möglich ist, hängt von Strecke und Verfügbarkeit ab, und das klären wir vorab und verbindlich."),
    ("Wie groß darf eine Direktfahrt-Sendung sein?",
     "Von der Dokumentenmappe bis zur vollen Transporterladung ist alles möglich. Bei größeren Mengen setzen wir ein entsprechend größeres Fahrzeug ein."),
  ],
  "related": ["stueckguttransport", "elektrogeraete-lieferung", "umzuege"],
 },
{
  "slug": "umzuege",
  "seo_title": "Umzug privat & gewerblich | RuhrCargo Dortmund",
  "seo_desc": "Umzug mit Spedition: Wir planen den Ablauf, stellen das passende Fahrzeug und bringen Hausrat oder Büro ans neue Ziel – privat und gewerblich, deutschlandweit.", "short": "Privat und gewerblich", "nav": "Umzüge", "title": "Umzüge",
  "icon": "i-home", "num": "06", "img": "ruhrcargo-umzug",
  "img_alt": "Mitarbeiter tragen eine Matratze durch ein Treppenhaus",
  "teaser": "Privat oder gewerblich – geplant, verladen und angekommen, ohne Stress für Sie.",
  "lead": "Vom Apartment bis zum Firmenstandort: Wir planen den Ablauf, stellen das passende Fahrzeug und bringen Ihren Hausrat oder Ihr Büro ans neue Ziel.",
  "body": [
    "Ein Umzug scheitert selten am Fahren. Er scheitert an der Planung: am zu kleinen Fahrzeug, am fehlenden Halteverbot, am Treppenhaus, das niemand vorher angesehen hat.",
    "Deshalb klären wir vorab, was tatsächlich zu bewegen ist und wie die Zugänge an beiden Adressen aussehen. Am Umzugstag geht es dann nur noch ums Tragen und Fahren.",
  ],
  "does": [
    "Private und gewerbliche Umzüge",
    "Fahrzeug passend zum tatsächlichen Volumen",
    "Verladen und Transport durch erfahrenes Personal",
    "Termin nach Ihrem Zeitplan",
    "Einzelne Möbelstücke bis zur kompletten Wohnung",
    "Vorabklärung von Zugang, Etage und Stellplatz",
  ],
  "who": ["Privathaushalte", "Büros und Praxen",
          "Filialen bei Standortwechsel", "Studierende und Einzelumzüge"],
  "vehicles": ["Möbelkoffer", "Koffer-LKW", "Kleintransporter"],
  "faq": [
    ("Wie finde ich heraus, welches Fahrzeug ich brauche?",
     "Das übernehmen wir. Beschreiben Sie uns grob, was mitkommt – Zimmerzahl, große Möbelstücke, Besonderheiten – und wir schlagen die passende Größe vor."),
    ("Übernehmen Sie auch Firmenumzüge?",
     "Ja. Büros, Praxen und Filialen ziehen meist außerhalb der Geschäftszeiten um. Den Termin richten wir danach aus."),
    ("Was ist mit besonders schweren Einzelstücken?",
     "Sagen Sie uns vorher Bescheid, etwa bei Klavier, Tresor oder Großgeräten. Dann planen wir Personal und Hilfsmittel entsprechend ein."),
  ],
  "related": ["neumoebel-lieferung", "elektrogeraete-lieferung", "kurierdienst"],
 },
]

SERVICE_BY_SLUG = {s["slug"]: s for s in SERVICES}

# ── Fuhrpark ──────────────────────────────────────────────────────────────
FLEET = [
{"slug": "kofferlkw", "img": "ruhrcargo-koffer-lkw", "wide": False,
  "label": "Klasse 02 · Mit Ladebordwand", "name": "Koffer-LKW",
  "alt": "Koffer-LKW von RuhrCargo mit ausgefahrener Ladebordwand beim Verladen eines Elektrogeräts",
  "tags": ["Elektrogeräte", "Neumöbel", "Stückgut"],
  "text": "Geschlossener Koffer mit Ladebordwand. Damit lässt sich schwere Ware ebenerdig verladen, ohne sie über die Bordkante zu heben – der Standard für Geräte und Möbel.",
  "specs": [("Einsatz", "Geräte, Möbel, empfindliche Ware"),
            ("Beladung", "Ladebordwand"),
            ("Besonderheit", "Wettergeschützter Koffer")]},
 {"slug": "moebelkoffer", "img": "ruhrcargo-moebelkoffer", "wide": False,
  "label": "Klasse 03 · Volumen", "name": "Möbelkoffer",
  "alt": "Zwei Mitarbeiter verladen ein verpacktes Möbelstück über die Ladebordwand",
  "tags": ["Neumöbel", "Umzüge", "Empfindliche Ware"],
  "text": "Großes Ladevolumen bei geringem Gewicht der Ladung. Das Fahrzeug für Möbel und Umzüge, wo es weniger auf Tonnen als auf Kubikmeter ankommt.",
  "specs": [("Einsatz", "Möbel und Umzugsgut"),
            ("Beladung", "Ladebordwand"),
            ("Besonderheit", "Maximales Volumen")]},
 {"slug": "transporter", "img": "ruhrcargo-kleintransporter", "wide": True,
  "label": "Klasse 04 · Wendig", "name": "Kleintransporter",
  "alt": "Kleintransporter von RuhrCargo mit geöffneten Hecktüren bei einer Zustellung",
  "tags": ["Kurierfahrten", "Direktfahrt", "Stückgut"],
  "text": "Kommt dorthin, wo größere Fahrzeuge nicht mehr hinkommen: enge Innenstadt, Hinterhof, Tiefgarage. Das Fahrzeug für Direktfahrten und Einzelzustellungen.",
  "specs": [("Einsatz", "Direktfahrten und Einzelsendungen"),
            ("Beladung", "Heck- und Seitentüren, Rampe"),
            ("Besonderheit", "Innenstadttauglich")]},
]

# ── Prozess ───────────────────────────────────────────────────────────────
STEPS = [
 ("01", "Anfrage", "Schnelle Rückmeldung",
  "Sie schildern uns Ladung, Strecke und Wunschtermin – telefonisch oder über das Formular.",
  ["Was transportiert wird, mit ungefähren Maßen und Gewicht",
   "Wo abgeholt und wo zugestellt werden soll",
   "Wann die Ware am Ziel sein muss",
   "Besonderheiten: Etage, Zufahrt, Zeitfenster"]),
 ("02", "Planung", "Disposition",
  "Wir wählen Fahrzeug, Route und Zeitfenster – und stimmen jedes Detail mit Ihnen ab.",
  ["Auswahl des passenden Fahrzeugs zur Ladung",
   "Routenplanung und realistische Zeitfenster",
   "Abstimmung von Zugang und Entlademöglichkeit",
   "Verbindliche Rückmeldung, bevor etwas losfährt"]),
 ("03", "Umsetzung", "Transport",
  "Verladen, gesichert, unterwegs. Ihr Ansprechpartner bleibt derselbe – von Start bis Ziel.",
  ["Fachgerechtes Verladen und Sichern der Ware",
   "Direktfahrt ohne unnötiges Umladen",
   "Erreichbarkeit während der Fahrt",
   "Rückmeldung bei Abweichungen, bevor Sie fragen müssen"]),
 ("04", "Lieferung", "Zustellung",
  "Termingerechte Zustellung am Ziel – sauber abgewickelt und vollständig dokumentiert.",
  ["Zustellung zum vereinbarten Termin",
   "Übergabe an den benannten Empfänger",
   "Dokumentation der Anlieferung",
   "Rückmeldung an Sie, dass die Ware angekommen ist"]),
]

REASONS = [
 ("01", "Zuverlässig", "Zugesagte Termine sind zugesagt. Ihre Ware kommt an – vollständig und unbeschädigt.",
  "Ein Transport ist erst dann gut gelaufen, wenn niemand darüber sprechen musste. Wir planen so, dass Zusagen halten, und melden uns von selbst, wenn sich etwas ändert."),
 ("02", "Flexibel", "Kurzfristige Anfrage, ungewöhnliche Ladung, enges Zeitfenster: Wir finden den Weg.",
  "Weil wir unsere Fahrzeuge selbst disponieren, können wir umplanen, ohne durch drei Instanzen zu gehen. Was möglich ist, sagen wir Ihnen sofort – und was nicht, ebenso."),
 ("03", "Erfahren", "Über 20 Jahre Praxis und ein Fachpersonal, das empfindliche Ware im Griff hat.",
  "Möbel, Elektrogeräte, Stückgut, Umzugsgut: Jede Ladungsart hat ihre Eigenheiten. Die lernt man nicht aus einem Handbuch, sondern über Jahre."),
 ("04", "Persönlich", "Kein Callcenter, keine Warteschleife. Sie erreichen die Menschen, die planen und fahren.",
  "Bei uns spricht man mit der Person, die den Auftrag auch disponiert. Das spart Erklärungsschleifen und sorgt dafür, dass Details nicht auf dem Weg verloren gehen."),
]

TIMELINE = [
 ("Etappe 01", "Der Anfang", "Ein Fahrzeug, ein Anspruch: Aufträge so ausführen, dass der Kunde wieder anruft."),
 ("Etappe 02", "Erste Festkunden", "Aus einzelnen Fahrten werden feste Touren für Handel und Industrie."),
 ("Etappe 03", "Spezialisierung", "Möbel, Elektrogeräte, Stückgut: Ladungsarten, die Erfahrung verlangen."),
 ("Etappe 04", "Heute", "Über 20 Fahrzeuge, erfahrenes Fachpersonal, deutschlandweit im Einsatz."),
]

SECTORS = ["Möbelhandel", "Elektrofachhandel", "Industrie & Produktion",
           "Handwerk", "Büros & Praxen", "Privatkunden"]
