# -*- coding: utf-8 -*-
"""Inhalte der RuhrCargo-Website. Einzige Quelle für alle Seitentexte."""

SITE = {
    "name": "RuhrCargo GmbH",
    "claim": "Ihre Ware. Unser Auftrag.",
    "domain": "https://www.ruhrcargo.de",
    # TODO:KONTAKT — echte Daten eintragen
    "phone_display": "+49 (0) 201 000 00 00",
    "phone_href": "+492010000000",
    "email": "info@ruhrcargo.de",
    "street": "Musterstraße 00",
    "zip_city": "45000 Essen",
    "hours": "Mo – Fr, 07:00 – 18:00 Uhr",
}

# ── Leistungen ────────────────────────────────────────────────────────────
SERVICES = [
 {
  "slug": "neumoebel", "short": "Möbel vom Lager bis in die Wohnung", "nav": "Neumöbel", "title": "Neumöbel",
  "icon": "i-sofa", "num": "01", "img": "leistung-neumoebel",
  "img_alt": "Zwei Mitarbeiter tragen ein verpacktes Sofa in einen Wohnraum",
  "teaser": "Empfindliche Neuware vom Lager bis zur Wunschadresse – sorgfältig verladen, sauber zugestellt.",
  "lead": "Neuware verzeiht keine Kratzer. Wir bringen Möbel vom Hersteller oder Lager bis zur Wunschadresse – gesichert, terminiert und ohne Umweg.",
  "body": [
    "Möbel sind sperrig, empfindlich und oft teuer. Ein Transportschaden kostet nicht nur Geld, sondern vor allem Zeit: für die Reklamation, für den Ersatz und für einen zweiten Anlauf. Deshalb behandeln wir Neumöbel wie das, was sie sind – Ware, die beim ersten Mal ankommen muss.",
    "Wir fahren für Möbelhäuser, Hersteller und Innenausstatter genauso wie für Privatkunden, die ihre Neuanschaffung nicht selbst transportieren wollen. Vom einzelnen Sessel bis zur kompletten Einrichtung.",
  ],
  "does": [
    "Abholung beim Hersteller, Lager oder Händler",
    "Ladungssicherung für empfindliche Oberflächen",
    "Transport im Möbelkoffer mit großem Ladevolumen",
    "Zustellung nach fester Terminabsprache",
    "Einzelstücke ebenso wie komplette Einrichtungen",
    "Feste Ansprechpartner von der Anfrage bis zur Lieferung",
  ],
  "who": ["Möbelhäuser und Fachhandel", "Hersteller und Zulieferer",
          "Innenausstatter und Raumausstatter", "Privatkunden mit Neuanschaffungen"],
  "vehicles": ["Möbelkoffer", "Koffer-LKW"],
  "faq": [
    ("Transportieren Sie auch einzelne Möbelstücke?",
     "Ja. Vom einzelnen Sessel bis zur kompletten Einrichtung. Sagen Sie uns, was zu transportieren ist – wir wählen das passende Fahrzeug dazu aus."),
    ("Wie wird die Ware gegen Schäden gesichert?",
     "Empfindliche Oberflächen werden abgedeckt, die Ladung im Fahrzeug so verzurrt, dass nichts verrutscht. Verpackte Neuware bleibt in ihrer Originalverpackung."),
    ("Können Sie in obere Etagen liefern?",
     "Sprechen Sie uns bei der Anfrage darauf an. Zugang, Etage und Treppenhaus klären wir vorab, damit vor Ort nichts improvisiert werden muss."),
  ],
  "related": ["umzuege", "elektrogeraete", "messe-ladenbau"],
 },
 {
  "slug": "elektrogeraete", "short": "Weiße Ware und Elektronik", "nav": "Elektrogeräte", "title": "Elektrogeräte",
  "icon": "i-appliance", "num": "02", "img": "leistung-elektrogeraete",
  "img_alt": "Mitarbeiter schiebt eine Waschmaschine über die Rampe in den Transporter",
  "teaser": "Weiße Ware und Elektronik sicher gesichert, sicher verladen und termingerecht zugestellt.",
  "lead": "Waschmaschine, Kühlschrank, Fernseher: Elektrogeräte sind schwer, empfindlich und schlecht zu greifen. Wir transportieren sie so, dass sie funktionsfähig ankommen.",
  "body": [
    "Weiße Ware verträgt weder harte Stöße noch falsche Lage. Wir sichern jedes Gerät einzeln, transportieren es aufrecht, wo das nötig ist, und stellen es am Ziel dort ab, wo es hingehört.",
    "Für den Fachhandel übernehmen wir wiederkehrende Touren zu Filialen und Endkunden. Für Privatkunden fahren wir Einzelgeräte – auch dann, wenn der Händler keine Lieferung anbietet.",
  ],
  "does": [
    "Einzelgeräte und komplette Filialbelieferungen",
    "Transportsicherung für empfindliche Technik",
    "Transport mit Ladebordwand statt Tragen über Bordkante",
    "Feste Touren für den Fachhandel auf Wunsch",
    "Zustellung nach Terminabsprache",
    "Abholung direkt beim Hersteller oder Großhandel",
  ],
  "who": ["Elektrofachhandel und Filialisten", "Küchenstudios",
          "Hersteller und Großhandel", "Privatkunden"],
  "vehicles": ["Koffer-LKW", "Kleintransporter"],
  "faq": [
    ("Übernehmen Sie auch wiederkehrende Filialbelieferungen?",
     "Ja. Feste Touren lassen sich planen und sind für beide Seiten kalkulierbar. Sprechen Sie uns auf Ihren Rhythmus an."),
    ("Wird das Gerät bis in die Wohnung gebracht?",
     "Das klären wir bei der Anfrage. Zugang, Etage und Stellplatz gehören zur Planung, damit vor Ort alles vorbereitet ist."),
    ("Was passiert bei einem Transportschaden?",
     "Wir dokumentieren die Übergabe. Melden Sie einen Schaden bitte direkt bei der Anlieferung, dann klären wir das Weitere unmittelbar mit Ihnen."),
  ],
  "related": ["neumoebel", "stueckgut", "kurierfahrten"],
 },
 {
  "slug": "stueckgut", "short": "Paletten, Kisten, Einzelsendungen", "nav": "Stückgut", "title": "Stückgut",
  "icon": "i-pallet", "num": "03", "img": "leistung-stueckgut",
  "img_alt": "Gabelstapler setzt eine folierte Palette im Lager ab",
  "teaser": "Paletten, Kisten und Einzelsendungen – flexibel gebündelt und deutschlandweit unterwegs.",
  "lead": "Von der Einzelpalette bis zur Teilladung: Wir bündeln Ihre Sendungen, planen die Route und liefern deutschlandweit – ohne Umweg über fremde Umschlagzentren.",
  "body": [
    "Stückgut über ein großes Netzwerk zu verschicken heißt: mehrfaches Umladen, viele Hände, wenig Kontrolle. Wir fahren stattdessen direkt. Ihre Palette wird einmal verladen und einmal abgeladen.",
    "Das ist besonders dann von Vorteil, wenn die Ware empfindlich ist, der Termin eng oder die Sendung zu groß für den Paketdienst und zu klein für eine Komplettladung.",
  ],
  "does": [
    "Einzelpaletten bis zur Teilladung",
    "Gitterboxen, Kisten und sperrige Einzelstücke",
    "Direktverkehr ohne Umladung",
    "Deutschlandweite Zustellung ab dem Ruhrgebiet",
    "Be- und Entladung per Gabelstapler oder Ladebordwand",
    "Feste Ansprechpartner in der Disposition",
  ],
  "who": ["Industrie und Produktion", "Groß- und Fachhandel",
          "Zulieferer", "Handwerksbetriebe"],
  "vehicles": ["LKW für Komplettladungen", "Koffer-LKW"],
  "faq": [
    ("Ab welcher Menge lohnt sich der Direktverkehr?",
     "Schon ab einer Palette, wenn Termin oder Empfindlichkeit der Ware im Vordergrund stehen. Wir sagen Ihnen ehrlich, wann eine andere Lösung günstiger ist."),
    ("Können Sie mehrere Empfänger auf einer Tour beliefern?",
     "Ja, das ist der Regelfall. Wir planen die Route so, dass die Reihenfolge zu Ihren Zeitfenstern passt."),
    ("Brauchen wir am Ziel einen Stapler?",
     "Nicht zwingend. Sagen Sie uns bei der Anfrage, wie am Empfangsort entladen werden kann – danach wählen wir das Fahrzeug aus."),
  ],
  "related": ["reifenlogistik", "elektrogeraete", "messe-ladenbau"],
 },
 {
  "slug": "kurierfahrten", "short": "Direktfahrt ohne Umladung", "nav": "Kurierfahrten", "title": "Kurierfahrten",
  "icon": "i-bolt", "num": "04", "img": "leistung-kurier",
  "img_alt": "Kurierfahrer bringt eine Sendung zu einem Bürogebäude, Transporter am Straßenrand",
  "teaser": "Direktfahrten, wenn es schnell gehen muss: ein Fahrzeug, eine Ladung, ein Ziel.",
  "lead": "Wenn ein Termin steht und die Sendung nicht warten kann: Ein Fahrzeug, eine Ladung, ein Ziel. Ohne Zwischenstopp, ohne Umladen.",
  "body": [
    "Die Direktfahrt ist die schnellste Form des Transports, weil sie die üblichen Zwischenschritte auslässt. Ihre Sendung wird bei Ihnen geladen und beim Empfänger abgeladen – dazwischen passiert nichts.",
    "Das ist die richtige Lösung für Ersatzteile, die eine Produktion am Laufen halten, für Unterlagen, die zu einem Termin vorliegen müssen, und für alles, wo ein verpasster Tag teurer ist als die Fahrt.",
  ],
  "does": [
    "Direktfahrt ohne Umladung und Zwischenlager",
    "Kurzfristige Beauftragung möglich",
    "Einzelsendungen bis zur Transporterladung",
    "Deutschlandweit, auch über Nacht geplant",
    "Feste Ansprechpartner während der Fahrt",
    "Auch für empfindliche und dokumentenpflichtige Ware",
  ],
  "who": ["Produktion und Instandhaltung", "Handel und Fachhandel",
          "Agenturen und Dienstleister", "Sanitätshäuser und Praxen"],
  "vehicles": ["Kleintransporter", "Koffer-LKW"],
  "faq": [
    ("Wie kurzfristig können Sie fahren?",
     "Das hängt davon ab, welches Fahrzeug frei ist. Rufen Sie an – am Telefon können wir Ihnen am schnellsten sagen, was heute noch machbar ist."),
    ("Fahren Sie auch nachts oder am Wochenende?",
     "Sprechen Sie uns auf Ihren Termin an. Was möglich ist, hängt von Strecke und Verfügbarkeit ab, und das klären wir vorab und verbindlich."),
    ("Wie groß darf eine Direktfahrt-Sendung sein?",
     "Von der Dokumentenmappe bis zur vollen Transporterladung ist alles möglich. Bei größeren Mengen setzen wir ein entsprechend größeres Fahrzeug ein."),
  ],
  "related": ["reha-hilfsmittel", "stueckgut", "elektrogeraete"],
 },
 {
  "slug": "reifenlogistik", "short": "Große Mengen in der Saison", "nav": "Reifenlogistik", "title": "Reifenlogistik",
  "icon": "i-tire", "num": "05", "img": "leistung-reifen",
  "img_alt": "Mitarbeiter erfasst Reifen vor dem beladenen LKW",
  "teaser": "Saisongeschäft ohne Stillstand: Reifen und Räder in Menge, pünktlich am Ziel.",
  "lead": "Zweimal im Jahr wollen alle gleichzeitig. Wir bewegen Reifen und Räder in großen Stückzahlen – planbar durch die Hochsaison.",
  "body": [
    "Reifenlogistik ist ein Mengengeschäft mit engem Zeitfenster. Wer im Wechselgeschäft nicht liefern kann, verliert den Umsatz an den Wettbewerb – nachholen lässt sich das nicht.",
    "Wir beliefern Handel, Werkstätten und Lager mit den Stückzahlen, die in der Saison gebraucht werden, und holen Altreifen auf derselben Tour wieder ab, wenn das gewünscht ist.",
  ],
  "does": [
    "Große Stückzahlen je Tour",
    "Belieferung von Handel, Werkstatt und Lager",
    "Abholung beim Großhandel und Hersteller",
    "Planbare Kapazitäten in der Wechselsaison",
    "Rückführung auf derselben Tour möglich",
    "Deutschlandweite Verteilung",
  ],
  "who": ["Reifengroßhandel", "Reifenfachhandel und Werkstätten",
          "Autohäuser", "Lager- und Einlagerungsbetriebe"],
  "vehicles": ["LKW für Komplettladungen", "Kleintransporter"],
  "faq": [
    ("Können Sie in der Hochsaison kurzfristig zusätzliche Touren fahren?",
     "Je früher wir Bescheid wissen, desto sicherer. Melden Sie Ihren Bedarf für die Wechselsaison am besten vorab an, dann halten wir die Kapazität frei."),
    ("Nehmen Sie Altreifen wieder mit?",
     "Wenn das vorab abgestimmt ist, ja. Die Rückführung auf derselben Tour spart Ihnen eine zweite Anfahrt."),
    ("Beliefern Sie auch einzelne Werkstätten?",
     "Ja. Wir fahren sowohl Großmengen an ein Lager als auch Verteiltouren zu mehreren Werkstätten."),
  ],
  "related": ["stueckgut", "kurierfahrten", "neumoebel"],
 },
 {
  "slug": "umzuege", "short": "Privat und gewerblich", "nav": "Umzüge", "title": "Umzüge",
  "icon": "i-home", "num": "06", "img": "leistung-umzuege",
  "img_alt": "Mitarbeiter tragen eine Matratze durch ein Treppenhaus",
  "teaser": "Privat oder gewerblich – geplant, verladen und angekommen, ohne Stress für Sie.",
  "lead": "Vom Apartment bis zum Firmenstandort: Wir planen den Ablauf, stellen das passende Fahrzeug und bringen Ihren Hausrat oder Ihr Büro ans neue Ziel.",
  "body": [
    "Ein Umzug scheitert selten am Fahren. Er scheitert an der Planung: am zu kleinen Fahrzeug, am fehlenden Halteverbot, am Treppenhaus, das niemand vorher angesehen hat.",
    "Deshalb klären wir vorab, was tatsächlich zu bewegen ist und wie die Zugänge an beiden Adressen aussehen. Am Umzugstag geht es dann nur noch ums Tragen und Fahren.",
  ],
  "does": [
    "Private und gewerbliche Umzüge",
    "Fahrzeug passend zum tatsächlichen Volumen",
    "Verladen und Transport durch erfahrenes Personal",
    "Termin nach Ihrem Zeitplan",
    "Einzelne Möbelstücke bis zur kompletten Wohnung",
    "Vorabklärung von Zugang, Etage und Stellplatz",
  ],
  "who": ["Privathaushalte", "Büros und Praxen",
          "Filialen bei Standortwechsel", "Studierende und Einzelumzüge"],
  "vehicles": ["Möbelkoffer", "Koffer-LKW", "Kleintransporter"],
  "faq": [
    ("Wie finde ich heraus, welches Fahrzeug ich brauche?",
     "Das übernehmen wir. Beschreiben Sie uns grob, was mitkommt – Zimmerzahl, große Möbelstücke, Besonderheiten – und wir schlagen die passende Größe vor."),
    ("Übernehmen Sie auch Firmenumzüge?",
     "Ja. Büros, Praxen und Filialen ziehen meist außerhalb der Geschäftszeiten um. Den Termin richten wir danach aus."),
    ("Was ist mit besonders schweren Einzelstücken?",
     "Sagen Sie uns vorher Bescheid, etwa bei Klavier, Tresor oder Großgeräten. Dann planen wir Personal und Hilfsmittel entsprechend ein."),
  ],
  "related": ["neumoebel", "elektrogeraete", "messe-ladenbau"],
 },
 {
  "slug": "messe-ladenbau", "short": "Termingenau im Zeitfenster", "nav": "Messe- & Ladenbau", "title": "Messe- & Ladenbau",
  "icon": "i-booth", "num": "07", "img": "leistung-messebau",
  "img_alt": "Mitarbeiter bauen einen Messestand mit RuhrCargo-Logowand auf",
  "teaser": "Termingenaue Anlieferung dort, wo Zeitfenster keine Verhandlungssache sind.",
  "lead": "Auf dem Messegelände und auf der Baustelle zählt das Zeitfenster. Wir liefern termingenau an – und holen nach dem Abbau wieder ab.",
  "body": [
    "Messebau und Ladenbau laufen nach einem Plan, der keine Puffer kennt. Wer sein Zeitfenster verpasst, steht hinten an und verliert einen halben Tag – manchmal den ganzen Aufbau.",
    "Wir kennen die Abläufe: Anmeldung, Zufahrt, Entladezone, Rückholung nach Abbauschluss. Ihre Ware ist da, wenn das Team da ist.",
  ],
  "does": [
    "Termingenaue Anlieferung im vereinbarten Zeitfenster",
    "An- und Abtransport aus einer Hand",
    "Transport von Standbau, Traversen und Flightcases",
    "Rückholung nach Abbauschluss",
    "Belieferung von Baustellen im Ladenbau",
    "Abstimmung mit Ihrem Aufbauteam vor Ort",
  ],
  "who": ["Messebauunternehmen", "Ladenbauer und Shopfitter",
          "Agenturen und Eventdienstleister", "Aussteller mit eigenem Stand"],
  "vehicles": ["LKW für Komplettladungen", "Koffer-LKW"],
  "faq": [
    ("Kennen Sie die Abläufe auf Messegeländen?",
     "Ja. Anmeldung, Zufahrtszeiten und Entladezonen gehören zur Planung, nicht zur Improvisation vor Ort."),
    ("Holen Sie nach dem Abbau wieder ab?",
     "Wenn das mitbeauftragt ist, ja. An- und Abtransport aus einer Hand erspart Ihnen die Koordination zweier Dienstleister."),
    ("Können Sie auch direkt an eine Ladenbaustelle liefern?",
     "Ja. Zufahrt, Entlademöglichkeit und Zeitfenster klären wir vorher, damit vor Ort niemand wartet."),
  ],
  "related": ["stueckgut", "neumoebel", "kurierfahrten"],
 },
 {
  "slug": "reha-hilfsmittel", "short": "Sensible Zustellungen", "nav": "Reha-Hilfsmittel", "title": "Reha-Hilfsmittel",
  "icon": "i-reha", "num": "08", "img": "leistung-reha",
  "img_alt": "Mitarbeiter begleitet eine Rollstuhlfahrerin über die Rampe in den Transporter",
  "teaser": "Sensible Zustellungen für Sanitätshäuser und Patienten – terminiert und mit Sorgfalt.",
  "lead": "Hilfsmittel gehen an Menschen, die darauf angewiesen sind. Wir liefern terminiert, diskret und mit der Ruhe, die diese Situation verlangt.",
  "body": [
    "Ein Rollstuhl, ein Pflegebett oder ein Rollator ist kein gewöhnliches Transportgut. Die Zustellung findet oft in einer schwierigen Lebenssituation statt, manchmal im Krankenhaus, manchmal zu Hause bei Angehörigen.",
    "Deshalb kommt es hier weniger auf Geschwindigkeit an als auf Verlässlichkeit und den richtigen Umgang. Ein zugesagter Termin muss halten, und der Fahrer muss wissen, wie er auftritt.",
  ],
  "does": [
    "Zustellung an Sanitätshaus, Klinik oder Patient",
    "Feste Terminabsprache statt Zeitfenster über den Tag",
    "Sorgfältiger Umgang mit sensibler Ware",
    "Abholung und Rückführung von Leihgeräten",
    "Diskretes Auftreten beim Endkunden",
    "Transport mit Ladebordwand für schwere Hilfsmittel",
  ],
  "who": ["Sanitätshäuser", "Kliniken und Reha-Einrichtungen",
          "Pflegedienste", "Hersteller von Hilfsmitteln"],
  "vehicles": ["Kleintransporter", "Koffer-LKW"],
  "faq": [
    ("Liefern Sie direkt an Patienten nach Hause?",
     "Ja. Der Termin wird vorher abgestimmt, damit jemand vor Ort ist und die Übergabe in Ruhe stattfinden kann."),
    ("Holen Sie Leihgeräte auch wieder ab?",
     "Ja, Rückführungen gehören zum Alltag in diesem Bereich. Das lässt sich mit einer Zustellung auf derselben Tour verbinden."),
    ("Wie gehen Sie mit schweren Hilfsmitteln um?",
     "Für Pflegebetten und ähnlich schwere Ware setzen wir Fahrzeuge mit Ladebordwand ein, damit nichts über die Bordkante gehoben werden muss."),
  ],
  "related": ["kurierfahrten", "elektrogeraete", "umzuege"],
 },
]

SERVICE_BY_SLUG = {s["slug"]: s for s in SERVICES}

# ── Fuhrpark ──────────────────────────────────────────────────────────────
FLEET = [
 {"slug": "lkw", "img": "fuhrpark-lkw", "wide": True,
  "label": "Klasse 01 · Schwer", "name": "LKW für Komplettladungen",
  "alt": "LKW von RuhrCargo wird in der Halle mit dem Gabelstapler beladen",
  "tags": ["Stückgut", "Paletten", "Reifenlogistik", "Messe- & Ladenbau"],
  "text": "Das größte Fahrzeug im Fuhrpark. Für Komplettladungen, Palettenmengen und alles, was in einen Transporter nicht mehr hineingeht. Be- und Entladung per Gabelstapler.",
  "specs": [("Einsatz", "Komplettladungen und große Teilladungen"),
            ("Beladung", "Gabelstapler, Rampe"),
            ("Reichweite", "Deutschlandweit")]},
 {"slug": "kofferlkw", "img": "fuhrpark-kofferlkw", "wide": False,
  "label": "Klasse 02 · Mit Ladebordwand", "name": "Koffer-LKW",
  "alt": "Koffer-LKW von RuhrCargo mit ausgefahrener Ladebordwand beim Verladen eines Elektrogeräts",
  "tags": ["Elektrogeräte", "Neumöbel", "Ladenbau"],
  "text": "Geschlossener Koffer mit Ladebordwand. Damit lässt sich schwere Ware ebenerdig verladen, ohne sie über die Bordkante zu heben – der Standard für Geräte und Möbel.",
  "specs": [("Einsatz", "Geräte, Möbel, empfindliche Ware"),
            ("Beladung", "Ladebordwand"),
            ("Besonderheit", "Wettergeschützter Koffer")]},
 {"slug": "moebelkoffer", "img": "fuhrpark-moebelkoffer", "wide": False,
  "label": "Klasse 03 · Volumen", "name": "Möbelkoffer",
  "alt": "Zwei Mitarbeiter verladen ein verpacktes Möbelstück über die Ladebordwand",
  "tags": ["Neumöbel", "Umzüge", "Empfindliche Ware"],
  "text": "Großes Ladevolumen bei geringem Gewicht der Ladung. Das Fahrzeug für Möbel und Umzüge, wo es weniger auf Tonnen als auf Kubikmeter ankommt.",
  "specs": [("Einsatz", "Möbel und Umzugsgut"),
            ("Beladung", "Ladebordwand"),
            ("Besonderheit", "Maximales Volumen")]},
 {"slug": "transporter", "img": "fuhrpark-transporter", "wide": True,
  "label": "Klasse 04 · Wendig", "name": "Kleintransporter",
  "alt": "Kleintransporter von RuhrCargo mit geöffneten Hecktüren bei einer Zustellung",
  "tags": ["Kurierfahrten", "Direktfahrt", "Reha-Hilfsmittel"],
  "text": "Kommt dorthin, wo größere Fahrzeuge nicht mehr hinkommen: enge Innenstadt, Hinterhof, Tiefgarage. Das Fahrzeug für Direktfahrten und Einzelzustellungen.",
  "specs": [("Einsatz", "Direktfahrten und Einzelsendungen"),
            ("Beladung", "Heck- und Seitentüren, Rampe"),
            ("Besonderheit", "Innenstadttauglich")]},
]

# ── Prozess ───────────────────────────────────────────────────────────────
STEPS = [
 ("01", "Anfrage", "Schnelle Rückmeldung",
  "Sie schildern uns Ladung, Strecke und Wunschtermin – telefonisch oder über das Formular.",
  ["Was transportiert wird, mit ungefähren Maßen und Gewicht",
   "Wo abgeholt und wo zugestellt werden soll",
   "Wann die Ware am Ziel sein muss",
   "Besonderheiten: Etage, Zufahrt, Zeitfenster"]),
 ("02", "Planung", "Disposition",
  "Wir wählen Fahrzeug, Route und Zeitfenster – und stimmen jedes Detail mit Ihnen ab.",
  ["Auswahl des passenden Fahrzeugs zur Ladung",
   "Routenplanung und realistische Zeitfenster",
   "Abstimmung von Zugang und Entlademöglichkeit",
   "Verbindliche Rückmeldung, bevor etwas losfährt"]),
 ("03", "Umsetzung", "Transport",
  "Verladen, gesichert, unterwegs. Ihr Ansprechpartner bleibt derselbe – von Start bis Ziel.",
  ["Fachgerechtes Verladen und Sichern der Ware",
   "Direktfahrt ohne unnötiges Umladen",
   "Erreichbarkeit während der Fahrt",
   "Rückmeldung bei Abweichungen, bevor Sie fragen müssen"]),
 ("04", "Lieferung", "Zustellung",
  "Termingerechte Zustellung am Ziel – sauber abgewickelt und vollständig dokumentiert.",
  ["Zustellung zum vereinbarten Termin",
   "Übergabe an den benannten Empfänger",
   "Dokumentation der Anlieferung",
   "Rückmeldung an Sie, dass die Ware angekommen ist"]),
]

REASONS = [
 ("01", "Zuverlässig", "Zugesagte Termine sind zugesagt. Ihre Ware kommt an – vollständig und unbeschädigt.",
  "Ein Transport ist erst dann gut gelaufen, wenn niemand darüber sprechen musste. Wir planen so, dass Zusagen halten, und melden uns von selbst, wenn sich etwas ändert."),
 ("02", "Flexibel", "Kurzfristige Anfrage, ungewöhnliche Ladung, enges Zeitfenster: Wir finden den Weg.",
  "Weil wir unsere Fahrzeuge selbst disponieren, können wir umplanen, ohne durch drei Instanzen zu gehen. Was möglich ist, sagen wir Ihnen sofort – und was nicht, ebenso."),
 ("03", "Erfahren", "Über 20 Jahre Praxis und ein Fachpersonal, das empfindliche Ware im Griff hat.",
  "Möbel, Elektrogeräte, Reifen, Hilfsmittel: Jede Ladungsart hat ihre Eigenheiten. Die lernt man nicht aus einem Handbuch, sondern über Jahre."),
 ("04", "Persönlich", "Kein Callcenter, keine Warteschleife. Sie erreichen die Menschen, die planen und fahren.",
  "Bei uns spricht man mit der Person, die den Auftrag auch disponiert. Das spart Erklärungsschleifen und sorgt dafür, dass Details nicht auf dem Weg verloren gehen."),
]

TIMELINE = [
 ("Etappe 01", "Der Anfang", "Ein Fahrzeug, ein Anspruch: Aufträge so ausführen, dass der Kunde wieder anruft."),
 ("Etappe 02", "Erste Festkunden", "Aus einzelnen Fahrten werden feste Touren für Handel und Industrie."),
 ("Etappe 03", "Spezialisierung", "Möbel, Elektrogeräte, Reifen, Reha: Ladungsarten, die Erfahrung verlangen."),
 ("Etappe 04", "Heute", "Über 20 Fahrzeuge, erfahrenes Fachpersonal, deutschlandweit im Einsatz."),
]

SECTORS = ["Möbelhandel", "Elektrofachhandel", "Reifengroßhandel", "Messebau",
           "Ladenbau", "Sanitätshäuser", "Industrie & Produktion", "Privatkunden"]
